### PR TITLE
refactor: refactor command runner to use yargs

### PR DESCRIPTION
**Pull request by ammmze**
yargs brings with it built-in help responses, tab completion, etc.

Examples:
```
❯ ./gluctl --help
gluctl <cmd> [args]

Commands:
  gluctl completion         generate completion script
  gluctl snapshot <action>  Manage snapshots

Options:
      --version  Show version number                                   [boolean]
  -h, --help     Show help                                             [boolean]
```

```
❯ ./gluctl snapshot --help
gluctl snapshot <action>

Manage snapshots

Positionals:
  action                                  [required] [choices: "create", "list"]

Options:
      --version          Show version number                           [boolean]
  -h, --help             Show help                                     [boolean]
  -a, --app              The app                             [string] [required]
  -n, --namespace        The namespace for the snapshot      [string] [required]
      --kopia-app        The name of the kopia app   [string] [default: "kopia"]
      --kopia-namespace  The namespace of kopia    [string] [default: "default"]
```

```
❯ ./gluctl snapshot list
gluctl snapshot <action>

Manage snapshots

Positionals:
  action                                  [required] [choices: "create", "list"]

Options:
      --version          Show version number                           [boolean]
  -h, --help             Show help                                     [boolean]
  -a, --app              The app                             [string] [required]
  -n, --namespace        The namespace for the snapshot      [string] [required]
      --kopia-app        The name of the kopia app   [string] [default: "kopia"]
      --kopia-namespace  The namespace of kopia    [string] [default: "default"] 

Missing required argument: app
```

I haven't actually setup any of this kopia stuff yet, but will probably be looking at it to switch off k10, so I get errors, but just to show that we are still getting into the command, here's what that looks like for me.
```
❯ ./gluctl snapshot list --app foo
file:///Users/brandencash/projects/gluctl/node_modules/zx/build/core.js:140
            let output = new ProcessOutput(code, signal, stdout, stderr, combined, message);
                         ^

ProcessOutput [Error]: Error from server (NotFound): deployments.apps "kopia" not found
    at Snapshot.list (file:///Users/brandencash/projects/gluctl/lib/Snapshot.mjs:73:30)
    exit code: 1
    at ChildProcess.<anonymous> (file:///Users/brandencash/projects/gluctl/node_modules/zx/build/core.js:140:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:482:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:482:12)
    at Pipe.<anonymous> (node:net:757:14)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17) {
  _code: 1,
  _signal: null,
  _stdout: '',
  _stderr: 'Error from server (NotFound): deployments.apps "kopia" not found\n',
  _combined: 'Error from server (NotFound): deployments.apps "kopia" not found\n'
}

Node.js v18.6.0
```

### CODE REVIEW

**Comment by ammmze** [comment]
Oops...guess I needed to update my branch ... one minute while i update it

**Comment by onedr0p** [comment]
I am happy with this change, but we'll need to update the docs to have npm install be a requirement to get up and running.

**Comment by onedr0p** [comment]
@jr0dd what do you think?

**Comment by jr0dd** [comment]
I definitely like what it can add. My only concern is that I just don't want it to open a can of worms for pr's from others with various other npm packages. @ammmze can you just update the readme so people will know to do a npm install? that will at least spare _some_ questions.

**Comment by onedr0p** [comment]
The can of worms are being open but it looks like they the power of caxa we can eventually static compile this thing into a single binary.

**Comment by jr0dd** [comment]
@ammmze just send another pr for readme. Not enough caffeine yet and merged already.

**Comment by onedr0p** [comment]
I also made @ammmze a collaborator on this repo.

**Comment by ammmze** [comment]
Awesome! Thanks guys! I'll get an update in the readme in a bit once I'm at my computer.

**Pull request merged**
